# Generated by Django 6.1.1 on 2026-09-29 00:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='descripcion')),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='localidad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='codigo postal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Casa', max_length=60, verbose_name='etiqueta')),
                ('name', models.CharField(max_length=160, verbose_name='destinatario')),
                ('address', models.CharField(max_length=255, verbose_name='direccion')),
                ('locality', models.CharField(max_length=100, verbose_name='localidad')),
                ('province', models.CharField(max_length=100, verbose_name='provincia')),
                ('postal_code', models.CharField(max_length=20, verbose_name='codigo postal')),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.customer')),
            ],
            options={
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('packed', 'Empacado'), ('in_transit', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('shipping_name', models.CharField(max_length=160)),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_locality', models.CharField(max_length=100)),
                ('shipping_province', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Tarjeta (simulacion)'), ('transfer', 'Transferencia')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Aprobado (simulado)'), ('failed', 'Rechazado')], default='completed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=80, unique=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio de venta')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio con descuento')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='imagen')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.orderplaced')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product')),
            ],
            options={
                'ordering': ['added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_product_per_user_cart')],
            },
        ),
    ]
