# Generated by Django 6.1.1 on 2026-09-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL de imagen'),
        ),
    ]
